--- #YAML:1.0
name:               Net-Nmsg
version:            0.04
abstract:           Perl extension for the NMSG message interchange library
author:
    - Matt Sisk <sisk@cert.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Math::Int64:        0
    NetAddr::IP::Util:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
